name: CI

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Install Tooling
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Format Check
        run: |
          goimports -l . | tee /tmp/fmt.out
          if [ -s /tmp/fmt.out ]; then
            echo "Please run: goimports -w ." && exit 1
          fi

      - name: Lint
        run: golangci-lint run ./...

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./... -timeout 2m -cover

      - name: Build (dev version)
        run: |
          go build -ldflags "-X 'nookli/cmd.version=dev' \
                             -X 'nookli/cmd.commit=$(git rev-parse --short HEAD)'" \
                   -o nookli

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nookli-${{ runner.os }}
          path: nookli
